// frontend/src/router/paths.ts
export const paths = {
  home: '/',
  browse: '/browse',
  search: '/search',
  contentDetail: (id: string) => `/content/${id}`,
  artistProfile: (username: string) => `/artist/${username}`,
  genre: (slug: string) => `/genre/${slug}`,
  playlist: (id: string) => `/playlist/${id}`,
  about: '/about',
  login: '/login',
  register: '/register',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  verifyEmail: '/verify-email',
  oauthCallback: '/oauth-callback',
  profile: '/profile',
  settings: '/settings',
  library: '/library',
  following: '/following',
  downloads: '/downloads',
  artist: {
    dashboard: '/artist/dashboard',
    content: '/artist/content',
    upload: '/artist/upload',
    editContent: (id: string) => `/artist/content/${id}/edit`,
    analytics: '/artist/analytics',
    followers: '/artist/followers',
    settings: '/artist/settings',
  },
  admin: {
    dashboard: '/admin',
    users: '/admin/users',
    userDetail: (id: string) => `/admin/users/${id}`,
    content: '/admin/content',
    moderation: '/admin/moderation',
    reports: '/admin/reports',
    analytics: '/admin/analytics',
    settings: '/admin/settings',
  },
};
